21,TypeError,'int' object is not callable,0,,2021-11-14 22:16:02.929285,"[('3(2)', 1)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/305253956.py"", line 1, in <module>', '    3(2)', ""TypeError: 'int' object is not callable""]"
22,AttributeError,'NoneType' object has no attribute 'hello',0,,2021-11-14 22:16:03.122267,"[('a.hello', 2)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/2399003099.py"", line 2, in <module>', '    a.hello', ""AttributeError: 'NoneType' object has no attribute 'hello'""]"
23,NameError,name 'data8' is not defined,0,,2021-11-14 22:16:03.286388,"[('data8', 15)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/4159590661.py"", line 15, in <module>', '    data8', ""NameError: name 'data8' is not defined""]"
24,SyntaxError,"invalid syntax (1866965863.py, line 1)",0,,2021-11-14 22:16:03.453913,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3143, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/1866965863.py"", line 1', '    2a', '     ^', 'SyntaxError: invalid syntax']"
25,AttributeError,module 'numpy' has no attribute 'aragne',0,,2021-11-14 22:16:03.602083,"[(""np.aragne('HI')"", 1), ('raise AttributeError(""module {!r} has no attribute ""', 313)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/1147446779.py"", line 1, in <module>', ""    np.aragne('HI')"", '  File ""/Users/divi/dsep/lib/python3.8/site-packages/numpy/__init__.py"", line 313, in __getattr__', '    raise AttributeError(""module {!r} has no attribute ""', ""AttributeError: module 'numpy' has no attribute 'aragne'""]"
26,IndexError,list index out of range,0,,2021-11-14 22:16:03.764988,"[('[2][1]', 1)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/1686336973.py"", line 1, in <module>', '    [2][1]', 'IndexError: list index out of range']"
27,AttributeError,module 'numpy' has no attribute 'hi',0,,2021-11-14 22:16:03.917816,"[('np.hi', 1), ('raise AttributeError(""module {!r} has no attribute ""', 313)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/1570163000.py"", line 1, in <module>', '    np.hi', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/numpy/__init__.py"", line 313, in __getattr__', '    raise AttributeError(""module {!r} has no attribute ""', ""AttributeError: module 'numpy' has no attribute 'hi'""]"
28,NameError,name 'Table' is not defined,0,,2021-11-14 22:16:04.064357,"[('Table()', 1)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/4234517321.py"", line 1, in <module>', '    Table()', ""NameError: name 'Table' is not defined""]"
29,ValueError,invalid literal for int() with base 10: 'HI',0,,2021-11-14 22:16:04.213243,"[('int(""HI"")', 1)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/532684827.py"", line 1, in <module>', '    int(""HI"")', ""ValueError: invalid literal for int() with base 10: 'HI'""]"
30,ZeroDivisionError,division by zero,0,,2021-11-14 22:16:04.381553,"[('f()', 4), ('1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 3 / 0', 2)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/3185432250.py"", line 4, in <module>', '    f()', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/3185432250.py"", line 2, in f', '    1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 3 / 0', 'ZeroDivisionError: division by zero']"
31,ZeroDivisionError,division by zero,0,,2021-11-14 22:16:04.571324,"[('g()', 2), ('g = lambda:f()', 1)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/1199893282.py"", line 2, in <module>', '    g()', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/1199893282.py"", line 1, in <lambda>', '    g = lambda:f()', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/3185432250.py"", line 2, in f', '    1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 3 / 0', 'ZeroDivisionError: division by zero']"
32,TypeError,'str' object cannot be interpreted as an integer,0,,2021-11-14 22:16:05.154673,"[('np.zeros((""23""))', 3)]","['Traceback (most recent call last):', '  File ""/Users/divi/dsep/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3444, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/var/folders/rj/c25q4n3534g4l32d2j4ml7g00000gn/T/ipykernel_64930/3299487035.py"", line 3, in <module>', '    np.zeros((""23""))', ""TypeError: 'str' object cannot be interpreted as an integer""]"
